<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Public library directory: profiles, cached catalogs, and follow relationships.
 *
 * library_profiles  - opt-in directory entries (node identity + visibility settings)
 * cached_catalogs   - hub-side ISBN cache for offline browsing of public libraries (TTL 7 days)
 * follows           - asymmetric follow graph (pending / active / rejected / blocked)
 */
final class Version20260301000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Public directory: library_profiles, cached_catalogs, follows';
    }

    public function up(Schema $schema): void
    {
        // Library profiles - one row per node that opts into the directory.
        // write_token is generated by the hub on first registration and returned
        // to the library. All subsequent write operations require it.
        $this->addSql('
            CREATE TABLE library_profiles (
                node_id       VARCHAR(128) NOT NULL PRIMARY KEY,
                write_token   VARCHAR(64)  NOT NULL,
                display_name  VARCHAR(255) NOT NULL,
                description   TEXT         DEFAULT NULL,
                book_count    INTEGER      NOT NULL DEFAULT 0,
                location_country VARCHAR(5) DEFAULT NULL,
                requires_approval BOOLEAN  NOT NULL DEFAULT 1,
                accept_from   VARCHAR(20)  NOT NULL DEFAULT \'everyone\',
                is_listed     BOOLEAN      NOT NULL DEFAULT 0,
                created_at    DATETIME     NOT NULL,
                last_seen_at  DATETIME     DEFAULT NULL
            )
        ');

        $this->addSql('CREATE INDEX idx_library_profiles_listed ON library_profiles (is_listed)');
        $this->addSql('CREATE INDEX idx_library_profiles_last_seen ON library_profiles (last_seen_at)');

        // Cached catalogs - ISBN list pushed by libraries that are public and open.
        // One row per library (1:1 with library_profiles), evicted after expires_at.
        // isbn_payload: JSON array - plaintext for open libraries, encrypted for approval-required.
        $this->addSql('
            CREATE TABLE cached_catalogs (
                node_id       VARCHAR(128) NOT NULL PRIMARY KEY,
                isbn_payload  TEXT         NOT NULL,
                updated_at    DATETIME     NOT NULL,
                expires_at    DATETIME     NOT NULL,
                FOREIGN KEY (node_id) REFERENCES library_profiles(node_id) ON DELETE CASCADE
            )
        ');

        $this->addSql('CREATE INDEX idx_cached_catalogs_expires ON cached_catalogs (expires_at)');

        // Follows - asymmetric follow graph between libraries.
        // A library authenticates with its write_token to create or manage follows.
        $this->addSql('
            CREATE TABLE follows (
                id                INTEGER      PRIMARY KEY AUTOINCREMENT NOT NULL,
                follower_node_id  VARCHAR(128) NOT NULL,
                followed_node_id  VARCHAR(128) NOT NULL,
                status            VARCHAR(20)  NOT NULL DEFAULT \'pending\',
                created_at        DATETIME     NOT NULL,
                resolved_at       DATETIME     DEFAULT NULL
            )
        ');

        $this->addSql('CREATE UNIQUE INDEX unique_follow ON follows (follower_node_id, followed_node_id)');
        $this->addSql('CREATE INDEX idx_follows_followed_status ON follows (followed_node_id, status)');
        $this->addSql('CREATE INDEX idx_follows_follower_status ON follows (follower_node_id, status)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS follows');
        $this->addSql('DROP TABLE IF EXISTS cached_catalogs');
        $this->addSql('DROP TABLE IF EXISTS library_profiles');
    }
}
