#!/usr/bin/env bash
# Deploy BiblioGenius Hub on VPS using Scaleway Secret Manager
# Usage: ./scripts/vps-deploy.sh [prod|staging] [service-name]
#
# This script:
# 1. Reads non-secret config from .env.{ENV}.config
# 2. Fetches secrets from Scaleway Secret Manager
# 3. Generates a temporary .env file (chmod 600)
# 4. Runs docker compose up
# 5. Removes the temporary .env file
#
# Secrets are stored in Scaleway Secret Manager with names:
#   hub-{ENV}-app-secret
#   hub-{ENV}-database-url
#   hub-{ENV}-health-token
#   hub-{ENV}-jira-api-token

set -euo pipefail

ENV="${1:-prod}"
SERVICE="${2:-hub-${ENV}}"
DEPLOY_DIR="/opt/hub"
CONFIG_FILE="${DEPLOY_DIR}/.env.${ENV}.config"
SECRETS_FILE="${DEPLOY_DIR}/.env.${ENV}"
SECRET_PREFIX="hub-${ENV}"

# Map staging service name
if [ "$ENV" = "staging" ]; then
    SERVICE="hub-staging"
fi

echo "==> Deploying ${SERVICE} (env: ${ENV})"

# --- Validate prerequisites ---
if ! command -v scw &> /dev/null; then
    echo "ERROR: Scaleway CLI (scw) not found. Install: https://github.com/scaleway/scaleway-cli"
    exit 1
fi

if [ ! -f "$CONFIG_FILE" ]; then
    echo "ERROR: Config file not found: ${CONFIG_FILE}"
    echo "Copy the template: cp .env.${ENV}.template ${CONFIG_FILE}"
    exit 1
fi

# --- Fetch secrets from Scaleway Secret Manager ---
echo "==> Fetching secrets from Scaleway Secret Manager (prefix: ${SECRET_PREFIX}-)..."

fetch_secret() {
    local name="$1"
    local value
    value=$(scw secret version access-by-path secret-name="${SECRET_PREFIX}-${name}" secret-path=/ revision=latest -o json 2>/dev/null | jq -r .data | base64 -d)
    if [ -z "$value" ]; then
        echo "ERROR: Failed to fetch secret '${SECRET_PREFIX}-${name}'" >&2
        exit 1
    fi
    echo "$value"
}

APP_SECRET=$(fetch_secret "app-secret")
DATABASE_URL=$(fetch_secret "database-url")
HEALTH_TOKEN=$(fetch_secret "health-token")
JIRA_API_TOKEN=$(fetch_secret "jira-api-token")

echo "    4/4 secrets fetched OK"

# --- Generate secrets-only .env file ---
# Non-secret config lives in .env.{ENV}.config (persistent on disk)
# This file contains ONLY secrets and is deleted after compose reads it
echo "==> Generating ${SECRETS_FILE} (secrets only)..."

cat > "$SECRETS_FILE" << SECRETS
# Auto-generated by vps-deploy.sh -- DO NOT EDIT
# Secrets fetched from Scaleway Secret Manager
APP_SECRET=${APP_SECRET}
DATABASE_URL=${DATABASE_URL}
HEALTH_TOKEN=${HEALTH_TOKEN}
JIRA_API_TOKEN=${JIRA_API_TOKEN}
SECRETS
chmod 600 "$SECRETS_FILE"

echo "    Generated with restricted permissions (600)"

# --- Pull and restart container ---
echo "==> Pulling latest image and restarting ${SERVICE}..."
cd "$DEPLOY_DIR"
docker compose pull "$SERVICE"
docker compose up -d "$SERVICE"

# --- Cleanup secrets file ---
echo "==> Cleaning up secrets file..."
rm -f "$SECRETS_FILE"

# --- Verify ---
echo "==> Waiting for container to start..."
sleep 45

if [ "$ENV" = "prod" ]; then
    PORT=8080
else
    PORT=8081
fi

HEALTH=$(curl -sf "http://localhost:${PORT}/api/health" 2>/dev/null || echo "FAIL")
if echo "$HEALTH" | grep -q '"status"'; then
    echo "==> Health check OK"
    echo "$HEALTH" | python3 -m json.tool 2>/dev/null || echo "$HEALTH"
else
    echo "==> WARNING: Health check failed. Check logs:"
    echo "    docker compose logs ${SERVICE} --tail 50"
    exit 1
fi

echo "==> Deployment complete for ${SERVICE}"
